import asyncio
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.database import AsyncSessionLocal
from app.models.models import Venue

# Sample venue data across Gujarat
VENUES_DATA = [
    # Ahmedabad
    {
        "name": "Sardar Patel Stadium Cricket Ground",
        "description": "World-class cricket stadium with modern facilities and excellent pitch conditions",
        "venue_type": "Stadium",
        "sports_available": ["Cricket"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "First Aid", "Floodlights", "Scoreboard"],
        "city": "Ahmedabad",
        "address": "Motera, Ahmedabad",
        "landmark": "Near Sabarmati River",
        "latitude": 23.0901,
        "longitude": 72.5953,
        "price_per_hour": 5000.0,
        "weekend_price": 7000.0,
        "peak_hour_price": 6000.0,
        "opening_time": "06:00",
        "closing_time": "22:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 132000,
        "surface_type": "Turf",
        "indoor_outdoor": "Outdoor",
        "images": ["/images/venues/sardar-patel.jpg"],
        "contact_number": "+919876543210",
        "email": "info@moterastadium.com",
        "rating": 4.8,
        "is_verified": True,
        "is_featured": True
    },
    {
        "name": "Elite Football Turf - Satellite",
        "description": "Premium artificial turf for 5-a-side and 7-a-side football matches",
        "venue_type": "Turf",
        "sports_available": ["Football", "Cricket"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "Floodlights", "Washroom"],
        "city": "Ahmedabad",
        "address": "Satellite Road, Ahmedabad",
        "landmark": "Near Jodhpur Cross Roads",
        "latitude": 23.0258,
        "longitude": 72.5098,
        "price_per_hour": 1200.0,
        "weekend_price": 1500.0,
        "peak_hour_price": 1800.0,
        "opening_time": "06:00",
        "closing_time": "23:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 14,
        "surface_type": "Artificial Turf",
        "indoor_outdoor": "Outdoor",
        "images": ["/images/venues/elite-turf.jpg"],
        "contact_number": "+919876543211",
        "rating": 4.5,
        "is_verified": True
    },
    {
        "name": "Badminton Arena - Vastrapur",
        "description": "Indoor badminton courts with wooden flooring and air conditioning",
        "venue_type": "Court",
        "sports_available": ["Badminton"],
        "amenities": ["Parking", "Changing Room", "Air Conditioning", "Equipment Rental", "Washroom"],
        "city": "Ahmedabad",
        "address": "Vastrapur Lake Area, Ahmedabad",
        "landmark": "Near Vastrapur Lake",
        "latitude": 23.0395,
        "longitude": 72.5262,
        "price_per_hour": 400.0,
        "weekend_price": 500.0,
        "peak_hour_price": 600.0,
        "opening_time": "06:00",
        "closing_time": "22:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 4,
        "surface_type": "Wooden",
        "indoor_outdoor": "Indoor",
        "images": ["/images/venues/badminton-arena.jpg"],
        "contact_number": "+919876543212",
        "rating": 4.6,
        "is_verified": True
    },
    {
        "name": "Play Sports Complex - SG Highway",
        "description": "Multi-sport complex with cricket nets, football turf, and basketball court",
        "venue_type": "Complex",
        "sports_available": ["Cricket", "Football", "Basketball", "Volleyball"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "Floodlights", "Equipment Rental", "Coaching"],
        "city": "Ahmedabad",
        "address": "SG Highway, Ahmedabad",
        "landmark": "Near Pakwan Circle",
        "latitude": 23.0368,
        "longitude": 72.5095,
        "price_per_hour": 800.0,
        "weekend_price": 1000.0,
        "peak_hour_price": 1200.0,
        "opening_time": "06:00",
        "closing_time": "23:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 20,
        "surface_type": "Mixed",
        "indoor_outdoor": "Both",
        "images": ["/images/venues/play-complex.jpg"],
        "contact_number": "+919876543213",
        "rating": 4.4,
        "is_verified": True
    },
    
    # Surat
    {
        "name": "Diamond City Sports Arena",
        "description": "State-of-the-art sports facility with multiple courts and turfs",
        "venue_type": "Arena",
        "sports_available": ["Cricket", "Football", "Badminton", "Table Tennis"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "Floodlights", "Pro Shop", "First Aid"],
        "city": "Surat",
        "address": "Vesu, Surat",
        "landmark": "Near VR Mall",
        "latitude": 21.1458,
        "longitude": 72.7694,
        "price_per_hour": 900.0,
        "weekend_price": 1200.0,
        "peak_hour_price": 1400.0,
        "opening_time": "06:00",
        "closing_time": "23:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 30,
        "surface_type": "Multi-Surface",
        "indoor_outdoor": "Both",
        "images": ["/images/venues/diamond-arena.jpg"],
        "contact_number": "+919876543214",
        "rating": 4.7,
        "is_verified": True,
        "is_featured": True
    },
    {
        "name": "Surat Premier League Turf",
        "description": "Professional football turf with FIFA standard grass",
        "venue_type": "Turf",
        "sports_available": ["Football"],
        "amenities": ["Parking", "Changing Room", "Floodlights", "Scoreboard"],
        "city": "Surat",
        "address": "Adajan, Surat",
        "landmark": "Near Pal RTO",
        "latitude": 21.1951,
        "longitude": 72.8066,
        "price_per_hour": 1500.0,
        "weekend_price": 2000.0,
        "peak_hour_price": 2200.0,
        "opening_time": "06:00",
        "closing_time": "23:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 14,
        "surface_type": "Artificial Grass",
        "indoor_outdoor": "Outdoor",
        "images": ["/images/venues/surat-turf.jpg"],
        "contact_number": "+919876543215",
        "rating": 4.5,
        "is_verified": True
    },
    
    # Vadodara
    {
        "name": "Baroda Cricket Academy Ground",
        "description": "Professional cricket ground with coaching facilities",
        "venue_type": "Ground",
        "sports_available": ["Cricket"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "Coaching", "Equipment Rental"],
        "city": "Vadodara",
        "address": "Fatehgunj, Vadodara",
        "landmark": "Near Sayajigunj",
        "latitude": 22.3072,
        "longitude": 73.1812,
        "price_per_hour": 1000.0,
        "weekend_price": 1300.0,
        "peak_hour_price": 1500.0,
        "opening_time": "06:00",
        "closing_time": "21:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 50,
        "surface_type": "Turf",
        "indoor_outdoor": "Outdoor",
        "images": ["/images/venues/baroda-cricket.jpg"],
        "contact_number": "+919876543216",
        "rating": 4.6,
        "is_verified": True
    },
    {
        "name": "Tennis Club Vadodara",
        "description": "Premium tennis courts with professional coaching",
        "venue_type": "Court",
        "sports_available": ["Tennis"],
        "amenities": ["Parking", "Changing Room", "Coaching", "Equipment Rental", "Cafeteria"],
        "city": "Vadodara",
        "address": "Alkapuri, Vadodara",
        "landmark": "Near Pratap Vilas Palace",
        "latitude": 22.3039,
        "longitude": 73.1812,
        "price_per_hour": 600.0,
        "weekend_price": 800.0,
        "peak_hour_price": 900.0,
        "opening_time": "06:00",
        "closing_time": "21:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 4,
        "surface_type": "Hard Court",
        "indoor_outdoor": "Outdoor",
        "images": ["/images/venues/tennis-club.jpg"],
        "contact_number": "+919876543217",
        "rating": 4.4,
        "is_verified": True
    },
    
    # Rajkot
    {
        "name": "Rajkot Sports Complex",
        "description": "Multi-purpose sports facility for various games",
        "venue_type": "Complex",
        "sports_available": ["Cricket", "Football", "Badminton", "Basketball", "Volleyball"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "Floodlights", "First Aid", "Pro Shop"],
        "city": "Rajkot",
        "address": "University Road, Rajkot",
        "landmark": "Near Saurashtra University",
        "latitude": 22.3039,
        "longitude": 70.8022,
        "price_per_hour": 700.0,
        "weekend_price": 900.0,
        "peak_hour_price": 1100.0,
        "opening_time": "06:00",
        "closing_time": "22:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 40,
        "surface_type": "Multi-Surface",
        "indoor_outdoor": "Both",
        "images": ["/images/venues/rajkot-complex.jpg"],
        "contact_number": "+919876543218",
        "rating": 4.3,
        "is_verified": True
    },
    {
        "name": "Striker Football Arena",
        "description": "Premium football turf with latest amenities",
        "venue_type": "Turf",
        "sports_available": ["Football"],
        "amenities": ["Parking", "Changing Room", "Floodlights", "Scoreboard", "Washroom"],
        "city": "Rajkot",
        "address": "150 Feet Ring Road, Rajkot",
        "landmark": "Near Yagnik Road",
        "latitude": 22.2912,
        "longitude": 70.7967,
        "price_per_hour": 1100.0,
        "weekend_price": 1400.0,
        "peak_hour_price": 1600.0,
        "opening_time": "06:00",
        "closing_time": "23:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 12,
        "surface_type": "Artificial Turf",
        "indoor_outdoor": "Outdoor",
        "images": ["/images/venues/striker-arena.jpg"],
        "contact_number": "+919876543219",
        "rating": 4.6,
        "is_verified": True
    },
    
    # Gandhinagar
    {
        "name": "Capital Sports Hub",
        "description": "Government-approved sports facility with all modern amenities",
        "venue_type": "Complex",
        "sports_available": ["Cricket", "Football", "Badminton", "Tennis", "Swimming"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "Floodlights", "Swimming Pool", "Gym"],
        "city": "Gandhinagar",
        "address": "Sector 21, Gandhinagar",
        "landmark": "Near State Assembly",
        "latitude": 23.2156,
        "longitude": 72.6369,
        "price_per_hour": 800.0,
        "weekend_price": 1000.0,
        "peak_hour_price": 1200.0,
        "opening_time": "06:00",
        "closing_time": "22:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 50,
        "surface_type": "Multi-Surface",
        "indoor_outdoor": "Both",
        "images": ["/images/venues/capital-hub.jpg"],
        "contact_number": "+919876543220",
        "rating": 4.7,
        "is_verified": True,
        "is_featured": True
    },
    
    # Bhavnagar
    {
        "name": "Bhavnagar Cricket Stadium",
        "description": "Historic cricket ground with excellent facilities",
        "venue_type": "Stadium",
        "sports_available": ["Cricket"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "Floodlights", "Scoreboard"],
        "city": "Bhavnagar",
        "address": "Crescent Circle, Bhavnagar",
        "landmark": "Near Victoria Park",
        "latitude": 21.7645,
        "longitude": 72.1519,
        "price_per_hour": 1500.0,
        "weekend_price": 2000.0,
        "peak_hour_price": 2200.0,
        "opening_time": "06:00",
        "closing_time": "21:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 30000,
        "surface_type": "Turf",
        "indoor_outdoor": "Outdoor",
        "images": ["/images/venues/bhavnagar-stadium.jpg"],
        "contact_number": "+919876543221",
        "rating": 4.4,
        "is_verified": True
    },
    
    # More venues across other cities...
    {
        "name": "Jamnagar Sports Academy",
        "description": "Comprehensive sports training facility",
        "venue_type": "Academy",
        "sports_available": ["Cricket", "Football", "Badminton", "Athletics"],
        "amenities": ["Parking", "Changing Room", "Cafeteria", "Coaching", "Medical Room"],
        "city": "Jamnagar",
        "address": "Aerodrome Road, Jamnagar",
        "landmark": "Near Airport",
        "latitude": 22.4707,
        "longitude": 70.0577,
        "price_per_hour": 600.0,
        "weekend_price": 800.0,
        "peak_hour_price": 900.0,
        "opening_time": "06:00",
        "closing_time": "21:00",
        "operating_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "capacity": 30,
        "surface_type": "Multi-Surface",
        "indoor_outdoor": "Both",
        "images": ["/images/venues/jamnagar-academy.jpg"],
        "contact_number": "+919876543222",
        "rating": 4.3,
        "is_verified": True
    }
]

async def seed_venues():
    """Seed the database with sample venues"""
    async with AsyncSessionLocal() as session:
        print("Starting venue seeding...")
        
        for venue_data in VENUES_DATA:
            venue = Venue(**venue_data)
            session.add(venue)
            print(f"Added: {venue_data['name']} in {venue_data['city']}")
        
        await session.commit()
        print(f"Successfully seeded {len(VENUES_DATA)} venues!")

if __name__ == "__main__":
    asyncio.run(seed_venues())

